on: [push]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install stable toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Run cargo check
        run: cargo +stable check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install stable toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Run cargo test
        run: cargo +stable test --all-features

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install stable toolchain
        run: rustup toolchain install stable --profile minimal --component rustfmt,clippy --no-self-update

      - name: Run cargo fmt
        run: cargo +stable fmt --all -- --check

      - name: Run cargo clippy
        run: cargo +stable clippy -- -D warnings
